export default {
  CHANGE_PRO_CHECKED: 'changeProChecked',
  INCREASE_NUM: 'increaseNum',
  REDUCE_NUM: 'reduceNum',
  GET_MALL_LIST: 'getMallList',
  ADD_TO_CART: 'addToCart',
  CHANGE_LOG_STATUS: 'changeLogStatus',
  STORAGR_USERINFO: 'storageUserinfo',
  CHANGE_HEADER: 'changeHeader',
  CHANGE_HASHEADER: 'changeHasHeader',
  CHANGE_HASTABBAR: 'changeHasTabbar',
  DELETE_CART_BY_ID: 'deleteCartById',
  ADD_TO_SEARCH: 'addToSearch',
  CLEAN_SEARCH_HISTORY: 'cleanSearchHistory',
};
